# Generated by Django 4.1.13 on 2024-03-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('college_id', models.CharField(max_length=15)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
    ]
